// scripts/admin/load-school-catchments.ts
/**
 * Load harvested school attendance-boundary polygons into geo_features
 * (kind='school_catchment'), joining each zone's school to the EQAO dataset
 * (data/ontario-schools.json) to attach school_id + PureProperty School Score.
 *
 * Inputs (kept in scripts/admin/ because data/ is regenerated by an external ETL):
 *   - school-catchments.geojson        (ArcGIS boards — harvest-school-catchments.mjs)
 *   - school-catchments-peel.geojson   (Peel SPS Plus — harvest-peel-catchments.mjs, optional)
 *   - school-catchment-sources.json    (registry: per-board license/source)
 *
 * The EQAO join is three-tier per zone, scoped to the same system + language:
 *   1. exact canonical-name match (within level when the panel is elementary/secondary),
 *   2. SPATIAL — the school point that falls inside the catchment (with a name-similarity
 *      tiebreak when several do),
 *   3. nearest same-panel school to the polygon centroid (≤3 km) as a last resort.
 *
 * Idempotent: DELETE FROM geo_features WHERE kind='school_catchment', then bulk insert
 * in one transaction; upserts one geo_sources row per board for attribution.
 *
 * Requires DATABASE_URL = Supabase Session pooler string (CLAUDE.md §12).
 * Run: npx tsx scripts/admin/load-school-catchments.ts
 */
import { Client } from "pg";
import * as fs from "fs";
import * as path from "path";
import dotenv from "dotenv";
dotenv.config({ path: [".env.local", ".env"] });

const HERE = __dirname;
const ROOT = path.join(HERE, "..", "..");
const GEOJSON = path.join(HERE, "school-catchments.geojson");
const SPSPLUS_GEOJSON = path.join(HERE, "school-catchments-spsplus.geojson"); // Peel + Hamilton Catholic
const TDSB_GEOJSON = path.join(HERE, "school-catchments-tdsb.geojson");
const CECCE_GEOJSON = path.join(HERE, "school-catchments-cecce.geojson");
const REGISTRY = path.join(HERE, "school-catchment-sources.json");
const SCHOOLS = path.join(ROOT, "data", "ontario-schools.json");

const INSERT_CHUNK = 200;

// Boards harvested outside the ArcGIS registry — provenance for geo_sources.
const EXTRA_SOURCES: Record<string, { name: string; url: string; license: string }> = {
  PDSB: {
    name: "Peel DSB",
    url: "https://www.peelschools.org/school-finder",
    license: "SPS Plus (peelschools.org) — no open-data license; confirm reuse terms with PDSB",
  },
  TDSB: {
    name: "Toronto DSB",
    url: "https://www.tdsb.on.ca/Find-your/School/By-Map",
    license: "TDSB Find-Your-School (tdsb.on.ca) — official boundaries, KML; confirm reuse terms with TDSB",
  },
  HWCDSB: {
    name: "Hamilton-Wentworth Catholic DSB",
    url: "https://www.hwcdsb.ca/school_life/school/school_locator_boundaries",
    license: "SPS Plus (hwcdsb.ca) — no open-data license; confirm reuse terms with HWCDSB",
  },
  CECCE: {
    name: "Conseil des écoles catholiques du Centre-Est",
    url: "https://www.ecolecatholique.ca/fr/Dans-Quelle-Ecole-Sinscrire_374",
    license: "CartoVista (ecolecatholique.ca) — no open-data license; confirm reuse terms with CECCE",
  },
};

interface Geometry { type: string; coordinates: number[][][] | number[][][][] }
interface CatchmentProps {
  boardCode: string; board: string; system: string; language: string;
  panel: string; year: string | null; school_name: string | null; source: string | null;
}
interface CatchmentFeature { type: "Feature"; geometry: Geometry | null; properties: CatchmentProps }
interface RawSchool {
  id: string; name: string;
  level: "elementary" | "secondary"; system: "public" | "catholic";
  language?: string; lat: number; lng: number; score: number | null;
}
interface SchoolRec {
  id: string; name: string; canon: string; tokens: Set<string>;
  level: "elementary" | "secondary"; system: string; language: string;
  lat: number; lng: number; score: number | null;
}

// ── name canonicalization ───────────────────────────────────────────────────
const STOP = new Set([
  "catholic", "public", "elementary", "secondary", "separate", "district", "school",
  "schools", "ecole", "cs", "ces", "ps", "ss", "es", "hs", "chs", "cvi", "ci", "si",
  "the", "of", "de", "la", "le", "and", "st", "saint", "temporary", "holding",
  "boundary", "catchment", "zone", "area", "jk", "sk", "grade", "grades",
]);
/** Strip parentheticals/brackets + grade-range noise before tokenizing. */
function cleanName(raw: string | null | undefined): string {
  return (raw ?? "")
    .replace(/\([^)]*\)/g, " ")
    .replace(/\[[^\]]*\]/g, " ")
    .replace(/\b\d{1,2}\s*-\s*\d{1,2}\b/g, " ") // "6-8", "25-26"
    .trim();
}
function tokens(s: string | null | undefined): string[] {
  return cleanName(s)
    .toLowerCase()
    .normalize("NFD").replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9 ]/g, " ")
    .split(/\s+/)
    .filter((t) => t && !STOP.has(t));
}
const canon = (s: string | null | undefined) => tokens(s).slice().sort().join(" ");
function jaccard(a: Set<string>, b: Set<string>): number {
  if (!a.size || !b.size) return 0;
  let inter = 0;
  for (const t of a) if (b.has(t)) inter++;
  return inter / (a.size + b.size - inter);
}
function panelToLevel(panel: string): "elementary" | "secondary" | null {
  if (panel === "elementary") return "elementary";
  if (panel === "secondary") return "secondary";
  return null; // combined / french / regular / french_immersion → level-agnostic
}

// ── geometry helpers (JS point-in-polygon over [lng,lat] rings) ──────────────
function pointInRing(x: number, y: number, ring: number[][]): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const xi = ring[i][0], yi = ring[i][1], xj = ring[j][0], yj = ring[j][1];
    if (((yi > y) !== (yj > y)) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}
function pointInGeom(x: number, y: number, g: Geometry): boolean {
  const polys = g.type === "Polygon" ? [g.coordinates as number[][][]]
    : g.type === "MultiPolygon" ? (g.coordinates as number[][][][]) : [];
  for (const poly of polys) {
    if (!poly?.[0] || !pointInRing(x, y, poly[0])) continue;
    let hole = false;
    for (let h = 1; h < poly.length; h++) if (pointInRing(x, y, poly[h])) { hole = true; break; }
    if (!hole) return true;
  }
  return false;
}
function bboxOf(g: Geometry): [number, number, number, number] {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  const polys = g.type === "Polygon" ? [g.coordinates as number[][][]]
    : g.type === "MultiPolygon" ? (g.coordinates as number[][][][]) : [];
  for (const poly of polys) for (const ring of poly) for (const [x, y] of ring) {
    if (x < minX) minX = x; if (x > maxX) maxX = x;
    if (y < minY) minY = y; if (y > maxY) maxY = y;
  }
  return [minX, minY, maxX, maxY];
}
function centroidOf(g: Geometry): [number, number] {
  const [minX, minY, maxX, maxY] = bboxOf(g);
  return [(minX + maxX) / 2, (minY + maxY) / 2];
}
function haversineKm(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371, dLat = ((lat2 - lat1) * Math.PI) / 180, dLng = ((lng2 - lng1) * Math.PI) / 180;
  const a = Math.sin(dLat / 2) ** 2 + Math.cos((lat1 * Math.PI) / 180) * Math.cos((lat2 * Math.PI) / 180) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}

function readFC(p: string): CatchmentFeature[] {
  if (!fs.existsSync(p)) return [];
  const fc = JSON.parse(fs.readFileSync(p, "utf-8")) as { features: CatchmentFeature[] };
  return Array.isArray(fc.features) ? fc.features : [];
}

const GEOM_EXPR =
  "ST_Multi(ST_CollectionExtract(ST_MakeValid(ST_SetSRID(ST_GeomFromGeoJSON(g), 4326)), 3))";

async function main() {
  const DATABASE_URL = process.env.DATABASE_URL || process.env.DIRECT_DB_URL;
  if (!DATABASE_URL) { console.error("❌ Set DATABASE_URL (Session pooler, §12)"); process.exit(1); }

  const features = [
    ...readFC(GEOJSON), ...readFC(SPSPLUS_GEOJSON), ...readFC(TDSB_GEOJSON), ...readFC(CECCE_GEOJSON),
  ];
  const registry = JSON.parse(fs.readFileSync(REGISTRY, "utf-8")) as {
    verified: Array<{ boardCode: string; board: string; sourcePage?: string; license?: string }>;
  };
  const schools = JSON.parse(fs.readFileSync(SCHOOLS, "utf-8")) as RawSchool[];
  const regByBoard = new Map(registry.verified.map((b) => [b.boardCode, b]));

  // School records + name indexes (canon scoped by system + language + level).
  const recs: SchoolRec[] = schools
    .filter((s) => Number.isFinite(s.lat) && Number.isFinite(s.lng))
    .map((s) => ({
      id: s.id, name: s.name, canon: canon(s.name), tokens: new Set(tokens(s.name)),
      level: s.level, system: s.system, language: (s.language ?? "english").toLowerCase(),
      lat: s.lat, lng: s.lng, score: s.score,
    }));
  const byKey = new Map<string, SchoolRec>();
  for (const r of recs) {
    if (!r.canon) continue;
    const k1 = `${r.system}|${r.language}|${r.level}|${r.canon}`;
    const k2 = `${r.system}|${r.language}|${r.canon}`;
    if (!byKey.has(k1)) byKey.set(k1, r);
    if (!byKey.has(k2)) byKey.set(k2, r);
  }

  function match(feat: CatchmentFeature): { rec: SchoolRec | null; confident: boolean } {
    const p = feat.properties, g = feat.geometry;
    const sys = p.system, lang = (p.language ?? "english").toLowerCase();
    const level = panelToLevel(p.panel);
    const c = canon(p.school_name);
    const ft = new Set(tokens(p.school_name));

    const nameHit =
      (level ? byKey.get(`${sys}|${lang}|${level}|${c}`) : undefined) ??
      byKey.get(`${sys}|${lang}|${c}`) ?? null;

    let chosen: SchoolRec | null = null;
    let viaName = false;
    if (g) {
      // Spatial: same system+language (+level if known) schools whose point is inside.
      const [minX, minY, maxX, maxY] = bboxOf(g);
      const inside: SchoolRec[] = [];
      for (const r of recs) {
        if (r.system !== sys || r.language !== lang) continue;
        if (level && r.level !== level) continue;
        if (r.lng < minX || r.lng > maxX || r.lat < minY || r.lat > maxY) continue;
        if (pointInGeom(r.lng, r.lat, g)) inside.push(r);
      }
      if (nameHit && inside.some((r) => r.id === nameHit.id)) { chosen = nameHit; viaName = true; }
      else if (inside.length === 1) chosen = inside[0];
      else if (inside.length > 1) {
        const best = inside.map((r) => ({ r, s: jaccard(ft, r.tokens) })).sort((a, b) => b.s - a.s)[0];
        chosen = best.s > 0 ? best.r : inside[0];
      } else if (nameHit) { chosen = nameHit; viaName = true; }
      else {
        // Last resort: nearest same-panel school to the centroid, within 3 km.
        const [cx, cy] = centroidOf(g);
        let near: SchoolRec | null = null, nd = Infinity;
        for (const r of recs) {
          if (r.system !== sys || r.language !== lang) continue;
          if (level && r.level !== level) continue;
          const d = haversineKm(cy, cx, r.lat, r.lng);
          if (d < nd) { nd = d; near = r; }
        }
        if (nd <= 3) chosen = near;
      }
    } else {
      chosen = nameHit;
      viaName = !!nameHit;
    }

    // Confidence gate for attaching the EQAO score: trust the match only when it's
    // name-based, the boundary carried no name (pure spatial), or the matched school
    // shares ≥1 name token. Prevents a WRONG score when the true school is absent from
    // the EQAO dataset (e.g. some French-board schools) and spatial grabbed a neighbour.
    const hasName = c.length > 0;
    const agree = chosen ? jaccard(ft, chosen.tokens) > 0 : false;
    const confident = !!chosen && (viaName || !hasName || agree);
    return { rec: chosen, confident };
  }

  // Build insert arrays + per-board provenance.
  const geoms: string[] = [], attrsArr: string[] = [], sourceKeys: string[] = [];
  const perBoard = new Map<string, { count: number; board: string; source: string | null }>();
  let matched = 0;
  for (const f of features) {
    if (!f.geometry) continue;
    const p = f.properties;
    const { rec: m, confident } = match(f);
    if (confident) matched++;
    geoms.push(JSON.stringify(f.geometry));
    attrsArr.push(JSON.stringify({
      boardCode: p.boardCode, board: p.board, system: p.system, language: p.language,
      panel: p.panel, year: p.year,
      school_name: p.school_name ?? (confident ? m?.name : null) ?? null,
      school_id: confident ? (m?.id ?? null) : null,
      score: confident ? (m?.score ?? null) : null,
      source: p.source,
    }));
    sourceKeys.push(`school_catchment:${p.boardCode}`);
    const cur = perBoard.get(p.boardCode);
    if (cur) cur.count++;
    else perBoard.set(p.boardCode, { count: 1, board: p.board, source: p.source });
  }

  console.log(`\n🏫 load-school-catchments → geo_features`);
  console.log(`   features: ${geoms.length}   EQAO-matched: ${matched} (${Math.round((matched / geoms.length) * 100)}%)   boards: ${perBoard.size}`);
  console.log("==================================================================\n");

  const client = new Client({ connectionString: DATABASE_URL, connectionTimeoutMillis: 15000, ssl: { rejectUnauthorized: false } });
  await client.connect();
  await client.query("SET statement_timeout TO '0'");
  try {
    await client.query("BEGIN");
    const del = await client.query("DELETE FROM geo_features WHERE kind = 'school_catchment'");
    if (del.rowCount) console.log(`   🗑️  cleared ${del.rowCount} existing catchment rows`);

    let inserted = 0;
    for (let i = 0; i < geoms.length; i += INSERT_CHUNK) {
      const r = await client.query(
        `INSERT INTO geo_features (kind, source_key, attrs, geom)
         SELECT 'school_catchment', sk, a, geom FROM (
           SELECT sk, a::jsonb AS a, ${GEOM_EXPR} AS geom
           FROM unnest($1::text[], $2::text[], $3::text[]) AS t(g, a, sk)
           WHERE g IS NOT NULL
         ) q
         WHERE q.geom IS NOT NULL AND NOT ST_IsEmpty(q.geom)`,
        [geoms.slice(i, i + INSERT_CHUNK), attrsArr.slice(i, i + INSERT_CHUNK), sourceKeys.slice(i, i + INSERT_CHUNK)]
      );
      inserted += r.rowCount ?? 0;
    }
    console.log(`   ✅ inserted ${inserted} catchment rows`);

    const today = new Date().toISOString().slice(0, 10);
    for (const [boardCode, info] of perBoard) {
      const reg = regByBoard.get(boardCode);
      const extra = EXTRA_SOURCES[boardCode];
      await client.query(
        `INSERT INTO geo_sources (key, kind, name, url, license, feature_count, retrieved_on)
         VALUES ($1, 'school_catchment', $2, $3, $4, $5, $6::date)
         ON CONFLICT (key) DO UPDATE
           SET name = EXCLUDED.name, url = EXCLUDED.url, license = EXCLUDED.license,
               feature_count = EXCLUDED.feature_count, retrieved_on = EXCLUDED.retrieved_on`,
        [
          `school_catchment:${boardCode}`,
          reg?.board ?? extra?.name ?? info.board ?? boardCode,
          reg?.sourcePage ?? extra?.url ?? info.source ?? null,
          reg?.license ?? extra?.license ?? "unspecified — confirm terms with board",
          info.count,
          today,
        ]
      );
    }
    await client.query("COMMIT");
    console.log(`   ✅ upserted ${perBoard.size} geo_sources provenance rows\n`);
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {});
    throw err;
  } finally {
    await client.end();
    console.log("🔌 Connection closed.\n");
  }
}

main().then(() => process.exit(0)).catch((e) => {
  console.error("❌ load-school-catchments failed:", e?.message || e);
  process.exit(1);
});
