/**
 * Seed `region_aliases` (migration 088) from the app's own membership lists.
 *
 * Ottawa is the only market that needs this today: its feed values are OREB AREA NAMES
 * ('Barrhaven', 'Kanata', 'Ottawa Centre'), which — unlike Toronto's 'Toronto C01' district
 * form — carry no pattern linking them to the municipality, so SQL cannot derive membership
 * and needs an explicit list.
 *
 * The list lives in src/lib/dashboard/ottawaAreas.ts (regenerated by derive-ottawa-cities.ts)
 * and is the SINGLE SOURCE OF TRUTH. This script mirrors it into Postgres, replacing the
 * region's rows wholesale so a regenerated list can never leave stale aliases behind.
 *
 * Toronto and London deliberately get NO rows: Toronto's districts and London's directionals
 * are already handled by regex inside the RPCs. Adding them here would be redundant work per
 * query with no behavioural change.
 *
 * Usage:
 *   npx tsx scripts/admin/seed-region-aliases.ts           # dry-run (shows the diff)
 *   npx tsx scripts/admin/seed-region-aliases.ts --apply    # write
 */
import { Client } from 'pg';
import dotenv from 'dotenv';
dotenv.config({ path: ['.env.local', '.env'] });

import { OTTAWA_AREAS } from '@/lib/dashboard/ottawaAreas';

const APPLY = process.argv.includes('--apply');
const DATABASE_URL = process.env.DATABASE_URL || process.env.DIRECT_DB_URL;
if (!DATABASE_URL) {
  console.error('❌ No DATABASE_URL');
  process.exit(1);
}

/** region (lowercase) → member city/area values as stored in the feed. */
const GROUPS: Record<string, string[]> = {
  ottawa: OTTAWA_AREAS,
};

async function main() {
  const client = new Client({
    connectionString: DATABASE_URL,
    connectionTimeoutMillis: 15000,
    ssl: { rejectUnauthorized: false },
  });
  await client.connect();
  console.log('✅ connected');
  console.log(`Mode: ${APPLY ? 'APPLY (writing)' : 'DRY-RUN (no writes)'}\n`);

  try {
    for (const [region, members] of Object.entries(GROUPS)) {
      const wanted = Array.from(
        new Set(members.map((m) => m.trim().toLowerCase()).filter(Boolean))
      ).sort();

      const { rows: existing } = await client.query<{ member_city: string }>(
        'SELECT member_city FROM region_aliases WHERE region = $1 ORDER BY member_city',
        [region]
      );
      const have = new Set(existing.map((r) => r.member_city));
      const toAdd = wanted.filter((w) => !have.has(w));
      const toDrop = [...have].filter((h) => !wanted.includes(h));

      console.log(`${region}: ${wanted.length} member(s) in source, ${have.size} in DB`);
      if (toAdd.length) console.log(`   + add  ${toAdd.length}: ${toAdd.slice(0, 5).join(', ')}${toAdd.length > 5 ? ' …' : ''}`);
      if (toDrop.length) console.log(`   - drop ${toDrop.length}: ${toDrop.slice(0, 5).join(', ')}${toDrop.length > 5 ? ' …' : ''}`);
      if (!toAdd.length && !toDrop.length) console.log('   (in sync)');

      if (!APPLY) continue;

      // Replace the region's rows wholesale inside a transaction: a regenerated source list
      // must never leave orphaned aliases silently widening a region.
      await client.query('BEGIN');
      try {
        await client.query('DELETE FROM region_aliases WHERE region = $1', [region]);
        if (wanted.length) {
          await client.query(
            'INSERT INTO region_aliases (region, member_city) SELECT $1, unnest($2::text[])',
            [region, wanted]
          );
        }
        await client.query('COMMIT');
        console.log(`   ✅ ${region}: ${wanted.length} alias row(s) written`);
      } catch (e) {
        await client.query('ROLLBACK');
        throw e;
      }
    }

    const { rows } = await client.query<{ region: string; n: string }>(
      'SELECT region, count(*)::text AS n FROM region_aliases GROUP BY region ORDER BY region'
    );
    console.log('\nregion_aliases now holds:', rows.map((r) => `${r.region}=${r.n}`).join(', ') || '(empty)');
  } finally {
    await client.end();
  }
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error('❌ failed:', e?.message || e);
    process.exit(1);
  });
