-- Migration 030: tiered rent index (neighbourhood+baths -> city+baths -> city)
-- Additive: existing rows remain valid until refreshRentalMarketIndex rebuilds.
ALTER TABLE rental_market_index ADD COLUMN IF NOT EXISTS match_tier TEXT;       -- 'nbhd' | 'city_bath' | 'city'
ALTER TABLE rental_market_index ADD COLUMN IF NOT EXISTS city TEXT;             -- municipality (listings.city)
ALTER TABLE rental_market_index ADD COLUMN IF NOT EXISTS bathrooms INTEGER;     -- BathroomsTotalInteger (real bath count)

-- City-level tiers have no neighbourhood; relax the NOT NULL.
ALTER TABLE rental_market_index ALTER COLUMN city_region DROP NOT NULL;

-- The old (city_region, sub_type, beds, washrooms_full) uniqueness no longer models the key.
-- Drop it (name auto-generated by migration 006's UNIQUE(...) → rental_market_index_city_region_..._key).
DO $$
DECLARE c text;
BEGIN
  SELECT conname INTO c FROM pg_constraint
   WHERE conrelid = 'rental_market_index'::regclass AND contype = 'u'
     AND pg_get_constraintdef(oid) LIKE '%washrooms_full%';
  IF c IS NOT NULL THEN EXECUTE format('ALTER TABLE rental_market_index DROP CONSTRAINT %I', c); END IF;
END $$;

-- Per-tier lookup indexes (partial). Table is small (≤ a few thousand rows), so these are instant.
CREATE INDEX IF NOT EXISTS idx_rmi_nbhd
  ON rental_market_index (city_region, property_sub_type, bedrooms_total, bathrooms)
  WHERE match_tier = 'nbhd';
CREATE INDEX IF NOT EXISTS idx_rmi_city_bath
  ON rental_market_index (city, property_sub_type, bedrooms_total, bathrooms)
  WHERE match_tier = 'city_bath';
CREATE INDEX IF NOT EXISTS idx_rmi_city
  ON rental_market_index (city, property_sub_type, bedrooms_total)
  WHERE match_tier = 'city';

-- Integrity: one row per (tier, dims). COALESCE so NULL city_region/bathrooms don't defeat uniqueness.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_rmi_tier
  ON rental_market_index (match_tier, COALESCE(city_region,''), COALESCE(city,''),
                          property_sub_type, bedrooms_total, COALESCE(bathrooms,-1));
